#!/bin/sh
#
# This loads the Database cache
#
java -cp target/Bidder-0.0.1-SNAPSHOT-jar-with-dependencies.jar com.jacamars.dsp.rtb.tools.ElasticLoader $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18}
