#!/bin/sh
#
# This runs the test bids/wins/clicks/pixels test program
#
java -Dlog4j.configuration="file:log4j.properties" -Xmx4096m -cp target/Bidder-0.0.1-SNAPSHOT-jar-with-dependencies.jar com.jacamars.dsp.rtb.tools.TestAccounting $1 $2 $3 $4
