#!/bin/sh
#
# This runs a cross pub/sub 0MQ broker
#
java -Dlog4j.configuration="file:log4j.properties" \
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=7001 \
-Xmx4096m -cp target/Bidder-0.0.1-SNAPSHOT-jar-with-dependencies.jar com.jacamars.dsp.rtb.services.Zerospike $1 $2 $3 $4 $5 $6 $7 $8 $9
